/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Analysis.Service.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Analysis.Service.ApiClient.Client.OpenAPIDateConverter;

namespace Analysis.Service.ApiClient.Model
{
    /// <summary>
    /// BindingConfiguration
    /// </summary>
    [DataContract(Name = "BindingConfiguration")]
    public partial class BindingConfiguration : IEquatable<BindingConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BindingConfiguration" /> class.
        /// </summary>
        /// <param name="targetService">targetService.</param>
        /// <param name="active">active.</param>
        public BindingConfiguration(string targetService = default(string), bool active = default(bool))
        {
            this.TargetService = targetService;
            this.Active = active;
        }

        /// <summary>
        /// Gets or Sets TargetService
        /// </summary>
        [DataMember(Name = "targetService", EmitDefaultValue = true)]
        public string TargetService { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "active", EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BindingConfiguration {\n");
            sb.Append("  TargetService: ").Append(TargetService).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BindingConfiguration);
        }

        /// <summary>
        /// Returns true if BindingConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of BindingConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BindingConfiguration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TargetService == input.TargetService ||
                    (this.TargetService != null &&
                    this.TargetService.Equals(input.TargetService))
                ) && 
                (
                    this.Active == input.Active ||
                    this.Active.Equals(input.Active)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TargetService != null)
                {
                    hashCode = (hashCode * 59) + this.TargetService.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Active.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
