/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Analysis.Service.ApiClient.Api;
using Analysis.Service.ApiClient.Model;
using Analysis.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Analysis.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing BindingConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BindingConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BindingConfiguration
        //private BindingConfiguration instance;

        public BindingConfigurationTests()
        {
            // TODO uncomment below to create an instance of BindingConfiguration
            //instance = new BindingConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BindingConfiguration
        /// </summary>
        [Fact]
        public void BindingConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" BindingConfiguration
            //Assert.IsType<BindingConfiguration>(instance);
        }


        /// <summary>
        /// Test the property 'TargetService'
        /// </summary>
        [Fact]
        public void TargetServiceTest()
        {
            // TODO unit test for the property 'TargetService'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

    }

}
