/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Analysis.Service.ApiClient.Api;
using Analysis.Service.ApiClient.Model;
using Analysis.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Analysis.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigurationChangeRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigurationChangeRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigurationChangeRequestDTO
        //private ConfigurationChangeRequestDTO instance;

        public ConfigurationChangeRequestDTOTests()
        {
            // TODO uncomment below to create an instance of ConfigurationChangeRequestDTO
            //instance = new ConfigurationChangeRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigurationChangeRequestDTO
        /// </summary>
        [Fact]
        public void ConfigurationChangeRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigurationChangeRequestDTO
            //Assert.IsType<ConfigurationChangeRequestDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Symptoms'
        /// </summary>
        [Fact]
        public void SymptomsTest()
        {
            // TODO unit test for the property 'Symptoms'
        }
        /// <summary>
        /// Test the property 'RequestedChanges'
        /// </summary>
        [Fact]
        public void RequestedChangesTest()
        {
            // TODO unit test for the property 'RequestedChanges'
        }

    }

}
