/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Analysis.Service.ApiClient.Api;
using Analysis.Service.ApiClient.Model;
using Analysis.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Analysis.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceConfigurationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceConfigurationDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceConfigurationDTO
        //private ServiceConfigurationDTO instance;

        public ServiceConfigurationDTOTests()
        {
            // TODO uncomment below to create an instance of ServiceConfigurationDTO
            //instance = new ServiceConfigurationDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceConfigurationDTO
        /// </summary>
        [Fact]
        public void ServiceConfigurationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceConfigurationDTO
            //Assert.IsType<ServiceConfigurationDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }
        /// <summary>
        /// Test the property 'IsDeployed'
        /// </summary>
        [Fact]
        public void IsDeployedTest()
        {
            // TODO unit test for the property 'IsDeployed'
        }
        /// <summary>
        /// Test the property 'ConfigurationProperties'
        /// </summary>
        [Fact]
        public void ConfigurationPropertiesTest()
        {
            // TODO unit test for the property 'ConfigurationProperties'
        }
        /// <summary>
        /// Test the property 'Bindings'
        /// </summary>
        [Fact]
        public void BindingsTest()
        {
            // TODO unit test for the property 'Bindings'
        }

    }

}
