/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Analysis.Service.ApiClient.Api;
using Analysis.Service.ApiClient.Model;
using Analysis.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Analysis.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing SymptomDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SymptomDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SymptomDTO
        //private SymptomDTO instance;

        public SymptomDTOTests()
        {
            // TODO uncomment below to create an instance of SymptomDTO
            //instance = new SymptomDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SymptomDTO
        /// </summary>
        [Fact]
        public void SymptomDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SymptomDTO
            //Assert.IsType<SymptomDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
