/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Analysis.Service.ApiClient.Client;
using Analysis.Service.ApiClient.Api;
// uncomment below to import models
//using Analysis.Service.ApiClient.Model;

namespace Analysis.Service.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing ConfigurationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConfigurationApiTests : IDisposable
    {
        private ConfigurationApi instance;

        public ConfigurationApiTests()
        {
            instance = new ConfigurationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigurationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConfigurationApi
            //Assert.IsType<ConfigurationApi>(instance);
        }

        /// <summary>
        /// Test ConfigurationRequestChangePost
        /// </summary>
        [Fact]
        public void ConfigurationRequestChangePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConfigurationChangeRequestDTO? configurationChangeRequestDTO = null;
            //instance.ConfigurationRequestChangePost(configurationChangeRequestDTO);
        }
    }
}
