/*
 * Analysis Service
 *
 * Demonstrates all the existing operations to access and manage Adaption Rules.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Analysis.Service.ApiClient.Client;
using Analysis.Service.ApiClient.Api;
// uncomment below to import models
//using Analysis.Service.ApiClient.Model;

namespace Analysis.Service.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing SystemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SystemApiTests : IDisposable
    {
        private SystemApi instance;

        public SystemApiTests()
        {
            instance = new SystemApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SystemApi
            //Assert.IsType<SystemApi>(instance);
        }

        /// <summary>
        /// Test SystemRequestChangePost
        /// </summary>
        [Fact]
        public void SystemRequestChangePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SystemConfigurationChangeRequestDTO? systemConfigurationChangeRequestDTO = null;
            //instance.SystemRequestChangePost(systemConfigurationChangeRequestDTO);
        }
    }
}
