{
 "title": "AdaptionLoop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Knowledge: Property Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(knowledge_service_property_get_requests_count{}[$__rate_interval])",
     "legendFormat": "Get property"
    },
    {
     "expr": "rate(knowledge_service_property_get_not_found_count{}[$__rate_interval])",
     "legendFormat": "Property not found"
    }
   ]
  },
  {
   "title": "Knowledge: Configuration Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(knowledge_service_configuration_get_requests_count{}[$__rate_interval])",
     "legendFormat": "Get configuration"
    },
    {
     "expr": "rate(knowledge_service_configuration_get_not_found_count{}[$__rate_interval])",
     "legendFormat": "Property not found"
    }
   ]
  },
  {
   "title": "Analysis: Rule execution rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(executed_rules[$__rate_interval]) / rate(evaluated_rules[$__rate_interval])",
     "legendFormat": "Execution Rate"
    }
   ]
  },
  {
   "title": "HTTP Request Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(source) (rate(http_requests_received_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Rule Evaluation rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(evaluated_rules{}[$__rate_interval])",
     "legendFormat": "Evaluated rules"
    },
    {
     "expr": "rate(executed_rules{}[$__rate_interval])",
     "legendFormat": "Executed rules"
    }
   ]
  }
 ]
}