/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Climatisation.Monitor.Service.ApiClient.Api;
using Climatisation.Monitor.Service.ApiClient.Model;
using Climatisation.Monitor.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Climatisation.Monitor.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigurationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigurationDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigurationDTO
        //private ConfigurationDTO instance;

        public ConfigurationDTOTests()
        {
            // TODO uncomment below to create an instance of ConfigurationDTO
            //instance = new ConfigurationDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigurationDTO
        /// </summary>
        [Fact]
        public void ConfigurationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigurationDTO
            //Assert.IsType<ConfigurationDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'LastModification'
        /// </summary>
        [Fact]
        public void LastModificationTest()
        {
            // TODO unit test for the property 'LastModification'
        }

    }

}
