/*
 * MonitoringService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using MonitoringService.ApiClient.Client;
using MonitoringService.ApiClient.Api;
// uncomment below to import models
//using MonitoringService.ApiClient.Model;

namespace MonitoringService.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing MonitorApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MonitorApiTests : IDisposable
    {
        private MonitorApi instance;

        public MonitorApiTests()
        {
            instance = new MonitorApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MonitorApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MonitorApi
            //Assert.IsType<MonitorApi>(instance);
        }

        /// <summary>
        /// Test MonitorMonitorIdMeasurementPost
        /// </summary>
        [Fact]
        public void MonitorMonitorIdMeasurementPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid monitorId = null;
            //MeasurementDTO measurementDTO = null;
            //instance.MonitorMonitorIdMeasurementPost(monitorId, measurementDTO);
        }
    }
}
