/*
 * Knowledge Service
 *
 * Demonstrates all the existing operations to access and manage Knowledge properties.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Knowledge.Service.ApiClient.Client;
using Knowledge.Service.ApiClient.Api;
// uncomment below to import models
//using Knowledge.Service.ApiClient.Model;

namespace Knowledge.Service.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing PropertyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PropertyApiTests : IDisposable
    {
        private PropertyApi instance;

        public PropertyApiTests()
        {
            instance = new PropertyApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertyApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PropertyApi
            //Assert.IsType<PropertyApi>(instance);
        }

        /// <summary>
        /// Test PropertyGet
        /// </summary>
        [Fact]
        public void PropertyGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PropertyGet();
            //Assert.IsType<Dictionary<string, PropertyDTO>>(response);
        }

        /// <summary>
        /// Test PropertyPropertyNameDelete
        /// </summary>
        [Fact]
        public void PropertyPropertyNameDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string propertyName = null;
            //instance.PropertyPropertyNameDelete(propertyName);
        }

        /// <summary>
        /// Test PropertyPropertyNameGet
        /// </summary>
        [Fact]
        public void PropertyPropertyNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string propertyName = null;
            //var response = instance.PropertyPropertyNameGet(propertyName);
            //Assert.IsType<PropertyDTO>(response);
        }

        /// <summary>
        /// Test PropertyPut
        /// </summary>
        [Fact]
        public void PropertyPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<SetPropertyDTO>? setPropertyDTO = null;
            //instance.PropertyPut(setPropertyDTO);
        }
    }
}
