/*
 * Monitoring Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Climatisation.AirConditioner.Service.ApiClient.Client;
using Climatisation.AirConditioner.Service.ApiClient.Api;

namespace Climatisation.AirConditioner.Service.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AirConditionerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AirConditionerApiTests : IDisposable
    {
        private AirConditionerApi instance;

        public AirConditionerApiTests()
        {
            instance = new AirConditionerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AirConditionerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AirConditionerApi
            //Assert.IsType<AirConditionerApi>(instance);
        }

        /// <summary>
        /// Test AirConditionerCoolPost
        /// </summary>
        [Fact]
        public void AirConditionerCoolPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.AirConditionerCoolPost();
        }

        /// <summary>
        /// Test AirConditionerHeatPost
        /// </summary>
        [Fact]
        public void AirConditionerHeatPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.AirConditionerHeatPost();
        }

        /// <summary>
        /// Test AirConditionerTurnOffPost
        /// </summary>
        [Fact]
        public void AirConditionerTurnOffPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.AirConditionerTurnOffPost();
        }
    }
}
