/*
 * MonitoringModule
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MonitoringModule.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = MonitoringModule.ApiClient.Client.OpenAPIDateConverter;

namespace MonitoringModule.ApiClient.Model
{
    /// <summary>
    /// PropertyDTO
    /// </summary>
    [DataContract(Name = "PropertyDTO")]
    public partial class PropertyDTO : IEquatable<PropertyDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyDTO" /> class.
        /// </summary>
        /// <param name="value">Gets or Sets Value.</param>
        /// <param name="lastModification">Gets or Sets LastModification.</param>
        public PropertyDTO(string value = default(string), DateTime lastModification = default(DateTime))
        {
            this.Value = value;
            this.LastModification = lastModification;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        /// <value>Gets or Sets Value</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets LastModification
        /// </summary>
        /// <value>Gets or Sets LastModification</value>
        [DataMember(Name = "lastModification", EmitDefaultValue = false)]
        public DateTime LastModification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PropertyDTO {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  LastModification: ").Append(LastModification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PropertyDTO);
        }

        /// <summary>
        /// Returns true if PropertyDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of PropertyDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PropertyDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.LastModification == input.LastModification ||
                    (this.LastModification != null &&
                    this.LastModification.Equals(input.LastModification))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.LastModification != null)
                    hashCode = hashCode * 59 + this.LastModification.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
