/*
 * RoomMonitor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RoomMonitor.ApiClient.Api;
using RoomMonitor.ApiClient.Model;
using RoomMonitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RoomMonitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing HumidityMeasurementDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HumidityMeasurementDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HumidityMeasurementDTO
        //private HumidityMeasurementDTO instance;

        public HumidityMeasurementDTOTests()
        {
            // TODO uncomment below to create an instance of HumidityMeasurementDTO
            //instance = new HumidityMeasurementDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HumidityMeasurementDTO
        /// </summary>
        [Fact]
        public void HumidityMeasurementDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" HumidityMeasurementDTO
            //Assert.IsType<HumidityMeasurementDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
