/*
 * Knowledge Service
 *
 * Demonstrates all the existing operations to access and manage Knowledge properties.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using KnowledgeService.ApiClient.Api;
using KnowledgeService.ApiClient.Model;
using KnowledgeService.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace KnowledgeService.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PropertyDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertyDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropertyDTO
        //private PropertyDTO instance;

        public PropertyDTOTests()
        {
            // TODO uncomment below to create an instance of PropertyDTO
            //instance = new PropertyDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertyDTO
        /// </summary>
        [Fact]
        public void PropertyDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropertyDTO
            //Assert.IsType<PropertyDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'LastModification'
        /// </summary>
        [Fact]
        public void LastModificationTest()
        {
            // TODO unit test for the property 'LastModification'
        }

    }

}
