/*
 * Monitoring Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Monitoring.Service.ApiClient.Api;
using Monitoring.Service.ApiClient.Model;
using Monitoring.Service.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Monitoring.Service.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing MeasurementDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeasurementDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeasurementDTO
        //private MeasurementDTO instance;

        public MeasurementDTOTests()
        {
            // TODO uncomment below to create an instance of MeasurementDTO
            //instance = new MeasurementDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeasurementDTO
        /// </summary>
        [Fact]
        public void MeasurementDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" MeasurementDTO
            //Assert.IsType<MeasurementDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ProbeId'
        /// </summary>
        [Fact]
        public void ProbeIdTest()
        {
            // TODO unit test for the property 'ProbeId'
        }
        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Fact]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }

    }

}
