/*
 * Knowledge Service
 *
 * Demonstrates all the existing operations to access and manage Knowledge properties.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using KnowledgeService.ApiClient.Client;
using KnowledgeService.ApiClient.Model;

namespace KnowledgeService.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertyApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a property given its name.
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <returns>PropertyDTO</returns>
        PropertyDTO PropertyPropertyNameGet(string propertyName);

        /// <summary>
        /// Gets a property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <returns>ApiResponse of PropertyDTO</returns>
        ApiResponse<PropertyDTO> PropertyPropertyNameGetWithHttpInfo(string propertyName);
        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created.
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns></returns>
        void PropertyPropertyNamePut(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO));

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PropertyPropertyNamePutWithHttpInfo(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertyApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets a property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PropertyDTO</returns>
        System.Threading.Tasks.Task<PropertyDTO> PropertyPropertyNameGetAsync(string propertyName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PropertyDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PropertyDTO>> PropertyPropertyNameGetWithHttpInfoAsync(string propertyName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PropertyPropertyNamePutAsync(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PropertyPropertyNamePutWithHttpInfoAsync(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPropertyApi : IPropertyApiSync, IPropertyApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PropertyApi : IDisposable, IPropertyApi
    {
        private KnowledgeService.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PropertyApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PropertyApi(string basePath)
        {
            this.Configuration = KnowledgeService.ApiClient.Client.Configuration.MergeConfigurations(
                KnowledgeService.ApiClient.Client.GlobalConfiguration.Instance,
                new KnowledgeService.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new KnowledgeService.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = KnowledgeService.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PropertyApi(KnowledgeService.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = KnowledgeService.ApiClient.Client.Configuration.MergeConfigurations(
                KnowledgeService.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new KnowledgeService.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = KnowledgeService.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertyApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertyApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = KnowledgeService.ApiClient.Client.Configuration.MergeConfigurations(
                KnowledgeService.ApiClient.Client.GlobalConfiguration.Instance,
                new KnowledgeService.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new KnowledgeService.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = KnowledgeService.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PropertyApi(HttpClient client, KnowledgeService.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = KnowledgeService.ApiClient.Client.Configuration.MergeConfigurations(
                KnowledgeService.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new KnowledgeService.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = KnowledgeService.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PropertyApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PropertyApi(KnowledgeService.ApiClient.Client.ISynchronousClient client, KnowledgeService.ApiClient.Client.IAsynchronousClient asyncClient, KnowledgeService.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = KnowledgeService.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public KnowledgeService.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public KnowledgeService.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public KnowledgeService.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public KnowledgeService.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public KnowledgeService.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets a property given its name. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <returns>PropertyDTO</returns>
        public PropertyDTO PropertyPropertyNameGet(string propertyName)
        {
            KnowledgeService.ApiClient.Client.ApiResponse<PropertyDTO> localVarResponse = PropertyPropertyNameGetWithHttpInfo(propertyName);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a property given its name. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <returns>ApiResponse of PropertyDTO</returns>
        public KnowledgeService.ApiClient.Client.ApiResponse<PropertyDTO> PropertyPropertyNameGetWithHttpInfo(string propertyName)
        {
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new KnowledgeService.ApiClient.Client.ApiException(400, "Missing required parameter 'propertyName' when calling PropertyApi->PropertyPropertyNameGet");

            KnowledgeService.ApiClient.Client.RequestOptions localVarRequestOptions = new KnowledgeService.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("propertyName", KnowledgeService.ApiClient.Client.ClientUtils.ParameterToString(propertyName)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<PropertyDTO>("/Property/{propertyName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PropertyPropertyNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a property given its name. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PropertyDTO</returns>
        public async System.Threading.Tasks.Task<PropertyDTO> PropertyPropertyNameGetAsync(string propertyName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            KnowledgeService.ApiClient.Client.ApiResponse<PropertyDTO> localVarResponse = await PropertyPropertyNameGetWithHttpInfoAsync(propertyName, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a property given its name. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PropertyDTO)</returns>
        public async System.Threading.Tasks.Task<KnowledgeService.ApiClient.Client.ApiResponse<PropertyDTO>> PropertyPropertyNameGetWithHttpInfoAsync(string propertyName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new KnowledgeService.ApiClient.Client.ApiException(400, "Missing required parameter 'propertyName' when calling PropertyApi->PropertyPropertyNameGet");


            KnowledgeService.ApiClient.Client.RequestOptions localVarRequestOptions = new KnowledgeService.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("propertyName", KnowledgeService.ApiClient.Client.ClientUtils.ParameterToString(propertyName)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PropertyDTO>("/Property/{propertyName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PropertyPropertyNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns></returns>
        public void PropertyPropertyNamePut(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO))
        {
            PropertyPropertyNamePutWithHttpInfo(propertyName, setPropertyDTO);
        }

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public KnowledgeService.ApiClient.Client.ApiResponse<Object> PropertyPropertyNamePutWithHttpInfo(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO))
        {
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new KnowledgeService.ApiClient.Client.ApiException(400, "Missing required parameter 'propertyName' when calling PropertyApi->PropertyPropertyNamePut");

            KnowledgeService.ApiClient.Client.RequestOptions localVarRequestOptions = new KnowledgeService.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("propertyName", KnowledgeService.ApiClient.Client.ClientUtils.ParameterToString(propertyName)); // path parameter
            localVarRequestOptions.Data = setPropertyDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/Property/{propertyName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PropertyPropertyNamePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PropertyPropertyNamePutAsync(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PropertyPropertyNamePutWithHttpInfoAsync(propertyName, setPropertyDTO, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Sets value of a given property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="KnowledgeService.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="propertyName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<KnowledgeService.ApiClient.Client.ApiResponse<Object>> PropertyPropertyNamePutWithHttpInfoAsync(string propertyName, SetPropertyDTO setPropertyDTO = default(SetPropertyDTO), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'propertyName' is set
            if (propertyName == null)
                throw new KnowledgeService.ApiClient.Client.ApiException(400, "Missing required parameter 'propertyName' when calling PropertyApi->PropertyPropertyNamePut");


            KnowledgeService.ApiClient.Client.RequestOptions localVarRequestOptions = new KnowledgeService.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = KnowledgeService.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("propertyName", KnowledgeService.ApiClient.Client.ClientUtils.ParameterToString(propertyName)); // path parameter
            localVarRequestOptions.Data = setPropertyDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/Property/{propertyName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PropertyPropertyNamePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
