/*
 * RoomMonitor
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using RoomMonitor.ApiClient.Client;
using RoomMonitor.ApiClient.Api;
// uncomment below to import models
//using RoomMonitor.ApiClient.Model;

namespace RoomMonitor.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing MeasurementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MeasurementApiTests : IDisposable
    {
        private MeasurementApi instance;

        public MeasurementApiTests()
        {
            instance = new MeasurementApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeasurementApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MeasurementApi
            //Assert.IsType<MeasurementApi>(instance);
        }

        /// <summary>
        /// Test MeasurementHumidityPost
        /// </summary>
        [Fact]
        public void MeasurementHumidityPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //HumidityMeasurementDTO humidityMeasurementDTO = null;
            //instance.MeasurementHumidityPost(humidityMeasurementDTO);
        }

        /// <summary>
        /// Test MeasurementTemperaturePost
        /// </summary>
        [Fact]
        public void MeasurementTemperaturePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TemperatureMeasurementDTO temperatureMeasurementDTO = null;
            //instance.MeasurementTemperaturePost(temperatureMeasurementDTO);
        }
    }
}
