/*
 * Knowledge Service
 *
 * Demonstrates all the existing operations to access and manage Knowledge properties.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Knowledge.Service.ApiClient.Client;
using Knowledge.Service.ApiClient.Model;

namespace Knowledge.Service.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>PropertyDTO</returns>
        PropertyDTO ConfigurationConfigurationNameGet(string configurationName);

        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ApiResponse of PropertyDTO</returns>
        ApiResponse<PropertyDTO> ConfigurationConfigurationNameGetWithHttpInfo(string configurationName);
        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system.
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <returns></returns>
        void ConfigurationRequestChangePost(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?));

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ConfigurationRequestChangePostWithHttpInfo(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PropertyDTO</returns>
        System.Threading.Tasks.Task<PropertyDTO> ConfigurationConfigurationNameGetAsync(string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PropertyDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PropertyDTO>> ConfigurationConfigurationNameGetWithHttpInfoAsync(string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ConfigurationRequestChangePostAsync(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ConfigurationRequestChangePostWithHttpInfoAsync(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConfigurationApi : IConfigurationApiSync, IConfigurationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ConfigurationApi : IDisposable, IConfigurationApi
    {
        private Knowledge.Service.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ConfigurationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ConfigurationApi(string basePath)
        {
            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Knowledge.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ConfigurationApi(Knowledge.Service.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ConfigurationApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ConfigurationApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Knowledge.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ConfigurationApi(HttpClient client, Knowledge.Service.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigurationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ConfigurationApi(Knowledge.Service.ApiClient.Client.ISynchronousClient client, Knowledge.Service.ApiClient.Client.IAsynchronousClient asyncClient, Knowledge.Service.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Knowledge.Service.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>PropertyDTO</returns>
        public PropertyDTO ConfigurationConfigurationNameGet(string configurationName)
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<PropertyDTO> localVarResponse = ConfigurationConfigurationNameGetWithHttpInfo(configurationName);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ApiResponse of PropertyDTO</returns>
        public Knowledge.Service.ApiClient.Client.ApiResponse<PropertyDTO> ConfigurationConfigurationNameGetWithHttpInfo(string configurationName)
        {
            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ConfigurationApi->ConfigurationConfigurationNameGet");

            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<PropertyDTO>("/Configuration/{configurationName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConfigurationConfigurationNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PropertyDTO</returns>
        public async System.Threading.Tasks.Task<PropertyDTO> ConfigurationConfigurationNameGetAsync(string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<PropertyDTO> localVarResponse = await ConfigurationConfigurationNameGetWithHttpInfoAsync(configurationName, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PropertyDTO)</returns>
        public async System.Threading.Tasks.Task<Knowledge.Service.ApiClient.Client.ApiResponse<PropertyDTO>> ConfigurationConfigurationNameGetWithHttpInfoAsync(string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ConfigurationApi->ConfigurationConfigurationNameGet");


            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PropertyDTO>("/Configuration/{configurationName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConfigurationConfigurationNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <returns></returns>
        public void ConfigurationRequestChangePost(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?))
        {
            ConfigurationRequestChangePostWithHttpInfo(configurationChangeRequestDTO);
        }

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Knowledge.Service.ApiClient.Client.ApiResponse<Object> ConfigurationRequestChangePostWithHttpInfo(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?))
        {
            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = configurationChangeRequestDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Configuration/request-change", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConfigurationRequestChangePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ConfigurationRequestChangePostAsync(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ConfigurationRequestChangePostWithHttpInfoAsync(configurationChangeRequestDTO, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Requests a change in a configuration key of a given service. For example,  could be used to set the target temperature of an AC system. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationChangeRequestDTO">The DTO containing the request to change the property. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Knowledge.Service.ApiClient.Client.ApiResponse<Object>> ConfigurationRequestChangePostWithHttpInfoAsync(ConfigurationChangeRequestDTO? configurationChangeRequestDTO = default(ConfigurationChangeRequestDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = configurationChangeRequestDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Configuration/request-change", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConfigurationRequestChangePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
