/*
 * Knowledge Service
 *
 * Demonstrates all the existing operations to access and manage Knowledge properties.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Knowledge.Service.ApiClient.Client;
using Knowledge.Service.ApiClient.Model;

namespace Knowledge.Service.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServiceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge.
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        Dictionary<string, Dictionary<string, ConfigurationDTO>> ServiceGet();

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>> ServiceGetWithHttpInfo();
        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ConfigurationDTO</returns>
        ConfigurationDTO ServiceServiceNameConfigurationConfigurationNameGet(string serviceName, string configurationName);

        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ApiResponse of ConfigurationDTO</returns>
        ApiResponse<ConfigurationDTO> ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfo(string serviceName, string configurationName);
        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created.
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns></returns>
        void ServiceServiceNameConfigurationConfigurationNamePut(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?));

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfo(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServiceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, ConfigurationDTO>>> ServiceGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>>> ServiceGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationDTO</returns>
        System.Threading.Tasks.Task<ConfigurationDTO> ServiceServiceNameConfigurationConfigurationNameGetAsync(string serviceName, string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets a configuration property given its name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConfigurationDTO>> ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfoAsync(string serviceName, string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ServiceServiceNameConfigurationConfigurationNamePutAsync(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfoAsync(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IServiceApi : IServiceApiSync, IServiceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ServiceApi : IDisposable, IServiceApi
    {
        private Knowledge.Service.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ServiceApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ServiceApi(string basePath)
        {
            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Knowledge.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ServiceApi(Knowledge.Service.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ServiceApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ServiceApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Knowledge.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ServiceApi(HttpClient client, Knowledge.Service.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Knowledge.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Knowledge.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Knowledge.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ServiceApi(Knowledge.Service.ApiClient.Client.ISynchronousClient client, Knowledge.Service.ApiClient.Client.IAsynchronousClient asyncClient, Knowledge.Service.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Knowledge.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Knowledge.Service.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Knowledge.Service.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        public Dictionary<string, Dictionary<string, ConfigurationDTO>> ServiceGet()
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>> localVarResponse = ServiceGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        public Knowledge.Service.ApiClient.Client.ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>> ServiceGetWithHttpInfo()
        {
            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request
            var localVarResponse = this.Client.Get<Dictionary<string, Dictionary<string, ConfigurationDTO>>>("/Service", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Dictionary<string, ConfigurationDTO>>> ServiceGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>> localVarResponse = await ServiceGetWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets all the service configuration properties registered in the knowledge. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Dictionary&lt;string, ConfigurationDTO&gt;&gt;)</returns>
        public async System.Threading.Tasks.Task<Knowledge.Service.ApiClient.Client.ApiResponse<Dictionary<string, Dictionary<string, ConfigurationDTO>>>> ServiceGetWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);



            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Dictionary<string, Dictionary<string, ConfigurationDTO>>>("/Service", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ConfigurationDTO</returns>
        public ConfigurationDTO ServiceServiceNameConfigurationConfigurationNameGet(string serviceName, string configurationName)
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<ConfigurationDTO> localVarResponse = ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfo(serviceName, configurationName);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <returns>ApiResponse of ConfigurationDTO</returns>
        public Knowledge.Service.ApiClient.Client.ApiResponse<ConfigurationDTO> ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfo(string serviceName, string configurationName)
        {
            // verify the required parameter 'serviceName' is set
            if (serviceName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'serviceName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNameGet");

            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNameGet");

            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(serviceName)); // path parameter
            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<ConfigurationDTO>("/Service/{serviceName}/configuration/{configurationName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceServiceNameConfigurationConfigurationNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConfigurationDTO</returns>
        public async System.Threading.Tasks.Task<ConfigurationDTO> ServiceServiceNameConfigurationConfigurationNameGetAsync(string serviceName, string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knowledge.Service.ApiClient.Client.ApiResponse<ConfigurationDTO> localVarResponse = await ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfoAsync(serviceName, configurationName, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a configuration property given its name. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service whose configuration we are looking for.</param>
        /// <param name="configurationName">The name of the configuration property to find.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConfigurationDTO)</returns>
        public async System.Threading.Tasks.Task<Knowledge.Service.ApiClient.Client.ApiResponse<ConfigurationDTO>> ServiceServiceNameConfigurationConfigurationNameGetWithHttpInfoAsync(string serviceName, string configurationName, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceName' is set
            if (serviceName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'serviceName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNameGet");

            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNameGet");


            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(serviceName)); // path parameter
            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ConfigurationDTO>("/Service/{serviceName}/configuration/{configurationName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceServiceNameConfigurationConfigurationNameGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns></returns>
        public void ServiceServiceNameConfigurationConfigurationNamePut(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?))
        {
            ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfo(serviceName, configurationName, setPropertyDTO);
        }

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Knowledge.Service.ApiClient.Client.ApiResponse<Object> ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfo(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?))
        {
            // verify the required parameter 'serviceName' is set
            if (serviceName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'serviceName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNamePut");

            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNamePut");

            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(serviceName)); // path parameter
            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter
            localVarRequestOptions.Data = setPropertyDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/Service/{serviceName}/configuration/{configurationName}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceServiceNameConfigurationConfigurationNamePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ServiceServiceNameConfigurationConfigurationNamePutAsync(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfoAsync(serviceName, configurationName, setPropertyDTO, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Sets value of a given configuration property. If the property does not exist, it will be created. 
        /// </summary>
        /// <exception cref="Knowledge.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="serviceName">The name of the service.</param>
        /// <param name="configurationName">The name of the property to set.</param>
        /// <param name="setPropertyDTO">The DTO containing the value to set. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Knowledge.Service.ApiClient.Client.ApiResponse<Object>> ServiceServiceNameConfigurationConfigurationNamePutWithHttpInfoAsync(string serviceName, string configurationName, SetPropertyDTO? setPropertyDTO = default(SetPropertyDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'serviceName' is set
            if (serviceName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'serviceName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNamePut");

            // verify the required parameter 'configurationName' is set
            if (configurationName == null)
                throw new Knowledge.Service.ApiClient.Client.ApiException(400, "Missing required parameter 'configurationName' when calling ServiceApi->ServiceServiceNameConfigurationConfigurationNamePut");


            Knowledge.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Knowledge.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Knowledge.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("serviceName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(serviceName)); // path parameter
            localVarRequestOptions.PathParameters.Add("configurationName", Knowledge.Service.ApiClient.Client.ClientUtils.ParameterToString(configurationName)); // path parameter
            localVarRequestOptions.Data = setPropertyDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/Service/{serviceName}/configuration/{configurationName}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ServiceServiceNameConfigurationConfigurationNamePut", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
