/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Climatisation.Monitor.ApiClient.Api;
using Climatisation.Monitor.ApiClient.Model;
using Climatisation.Monitor.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Climatisation.Monitor.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TemperatureUnit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemperatureUnitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemperatureUnit
        //private TemperatureUnit instance;

        public TemperatureUnitTests()
        {
            // TODO uncomment below to create an instance of TemperatureUnit
            //instance = new TemperatureUnit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemperatureUnit
        /// </summary>
        [Fact]
        public void TemperatureUnitInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemperatureUnit
            //Assert.IsType<TemperatureUnit>(instance);
        }



    }

}
