/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Climatisation.Monitor.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Climatisation.Monitor.ApiClient.Client.OpenAPIDateConverter;

namespace Climatisation.Monitor.ApiClient.Model
{
    /// <summary>
    /// Defines HumidityUnit
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum HumidityUnit
    {
        /// <summary>
        /// Enum RELATIVE for value: RELATIVE
        /// </summary>
        [EnumMember(Value = "RELATIVE")]
        RELATIVE = 1,

        /// <summary>
        /// Enum ABSOLUTE for value: ABSOLUTE
        /// </summary>
        [EnumMember(Value = "ABSOLUTE")]
        ABSOLUTE = 2

    }

}
