/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Climatisation.Monitor.Service.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = Climatisation.Monitor.Service.ApiClient.Client.OpenAPIDateConverter;

namespace Climatisation.Monitor.Service.ApiClient.Model
{
    /// <summary>
    /// Defines TemperatureUnit
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TemperatureUnit
    {
        /// <summary>
        /// Enum KELVIN for value: KELVIN
        /// </summary>
        [EnumMember(Value = "KELVIN")]
        KELVIN = 1,

        /// <summary>
        /// Enum CELSIUS for value: CELSIUS
        /// </summary>
        [EnumMember(Value = "CELSIUS")]
        CELSIUS = 2,

        /// <summary>
        /// Enum FAHRENHEIT for value: FAHRENHEIT
        /// </summary>
        [EnumMember(Value = "FAHRENHEIT")]
        FAHRENHEIT = 3

    }

}
