/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Climatisation.Monitor.Service.ApiClient.Client;
using Climatisation.Monitor.Service.ApiClient.Model;

namespace Climatisation.Monitor.Service.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeasurementApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <returns></returns>
        void MeasurementHumidityPost(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> MeasurementHumidityPostWithHttpInfo(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <returns></returns>
        void MeasurementTemperaturePost(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> MeasurementTemperaturePostWithHttpInfo(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeasurementApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task MeasurementHumidityPostAsync(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> MeasurementHumidityPostWithHttpInfoAsync(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task MeasurementTemperaturePostAsync(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> MeasurementTemperaturePostWithHttpInfoAsync(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeasurementApi : IMeasurementApiSync, IMeasurementApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MeasurementApi : IDisposable, IMeasurementApi
    {
        private Climatisation.Monitor.Service.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MeasurementApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MeasurementApi(string basePath)
        {
            this.Configuration = Climatisation.Monitor.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Climatisation.Monitor.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Climatisation.Monitor.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Climatisation.Monitor.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Climatisation.Monitor.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MeasurementApi(Climatisation.Monitor.Service.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Climatisation.Monitor.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Climatisation.Monitor.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Climatisation.Monitor.Service.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Climatisation.Monitor.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MeasurementApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MeasurementApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Climatisation.Monitor.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Climatisation.Monitor.Service.ApiClient.Client.GlobalConfiguration.Instance,
                new Climatisation.Monitor.Service.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Climatisation.Monitor.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Climatisation.Monitor.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MeasurementApi(HttpClient client, Climatisation.Monitor.Service.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Climatisation.Monitor.Service.ApiClient.Client.Configuration.MergeConfigurations(
                Climatisation.Monitor.Service.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Climatisation.Monitor.Service.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Climatisation.Monitor.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeasurementApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MeasurementApi(Climatisation.Monitor.Service.ApiClient.Client.ISynchronousClient client, Climatisation.Monitor.Service.ApiClient.Client.IAsynchronousClient asyncClient, Climatisation.Monitor.Service.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Climatisation.Monitor.Service.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Climatisation.Monitor.Service.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Climatisation.Monitor.Service.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Climatisation.Monitor.Service.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Climatisation.Monitor.Service.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Climatisation.Monitor.Service.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <returns></returns>
        public void MeasurementHumidityPost(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?))
        {
            MeasurementHumidityPostWithHttpInfo(humidityMeasurementDTO);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Climatisation.Monitor.Service.ApiClient.Client.ApiResponse<Object> MeasurementHumidityPostWithHttpInfo(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?))
        {
            Climatisation.Monitor.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Climatisation.Monitor.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = humidityMeasurementDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Measurement/Humidity", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MeasurementHumidityPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task MeasurementHumidityPostAsync(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await MeasurementHumidityPostWithHttpInfoAsync(humidityMeasurementDTO, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="humidityMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Climatisation.Monitor.Service.ApiClient.Client.ApiResponse<Object>> MeasurementHumidityPostWithHttpInfoAsync(HumidityMeasurementDTO? humidityMeasurementDTO = default(HumidityMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Climatisation.Monitor.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Climatisation.Monitor.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = humidityMeasurementDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Measurement/Humidity", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MeasurementHumidityPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <returns></returns>
        public void MeasurementTemperaturePost(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?))
        {
            MeasurementTemperaturePostWithHttpInfo(temperatureMeasurementDTO);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Climatisation.Monitor.Service.ApiClient.Client.ApiResponse<Object> MeasurementTemperaturePostWithHttpInfo(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?))
        {
            Climatisation.Monitor.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Climatisation.Monitor.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = temperatureMeasurementDTO;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/Measurement/Temperature", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MeasurementTemperaturePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task MeasurementTemperaturePostAsync(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await MeasurementTemperaturePostWithHttpInfoAsync(temperatureMeasurementDTO, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Climatisation.Monitor.Service.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="temperatureMeasurementDTO"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Climatisation.Monitor.Service.ApiClient.Client.ApiResponse<Object>> MeasurementTemperaturePostWithHttpInfoAsync(TemperatureMeasurementDTO? temperatureMeasurementDTO = default(TemperatureMeasurementDTO?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Climatisation.Monitor.Service.ApiClient.Client.RequestOptions localVarRequestOptions = new Climatisation.Monitor.Service.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Climatisation.Monitor.Service.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = temperatureMeasurementDTO;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/Measurement/Temperature", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MeasurementTemperaturePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
