/*
 * Room Monitor Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Climatisation.Monitor.Service.ApiClient.Client;
using Climatisation.Monitor.Service.ApiClient.Api;
// uncomment below to import models
//using Climatisation.Monitor.Service.ApiClient.Model;

namespace Climatisation.Monitor.Service.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing ServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ServiceApiTests : IDisposable
    {
        private ServiceApi instance;

        public ServiceApiTests()
        {
            instance = new ServiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ServiceApi
            //Assert.IsType<ServiceApi>(instance);
        }

        /// <summary>
        /// Test ServiceServiceNameConfigurationConfigurationNameGet
        /// </summary>
        [Fact]
        public void ServiceServiceNameConfigurationConfigurationNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceName = null;
            //string configurationName = null;
            //var response = instance.ServiceServiceNameConfigurationConfigurationNameGet(serviceName, configurationName);
            //Assert.IsType<ConfigurationDTO>(response);
        }

        /// <summary>
        /// Test ServiceServiceNameConfigurationPut
        /// </summary>
        [Fact]
        public void ServiceServiceNameConfigurationPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string serviceName = null;
            //List<SetPropertyDTO>? setPropertyDTO = null;
            //instance.ServiceServiceNameConfigurationPut(serviceName, setPropertyDTO);
        }
    }
}
