
# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:

- name: Jaeger
  type: jaeger
  access: proxy
  orgId: 1
  uid: fL84zbLnz
  url: http://jaeger:16686
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  readOnly: true
  version: 1

- name: Loki
  type: loki
  access: proxy
  orgId: 1
  uid: sH27zbL7z
  url: http://loki:3100
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: true
  jsonData:
    derivedFields:
      - datasourceUid: fL84zbLnz
        matcherRegex: '] (\w+)'
        name: TracerId
        url: '$${__value.raw}'
  readOnly: true
  version: 1

- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  uid: 4x1ifEU7k
  url: http://prometheus:9090/
  password: ''
  user: ''
  database: ''
  basicAuth: false
  isDefault: false
  jsonData:
    httpMethod: POST
  readOnly: true
  version: 1
